"""add card topic association

Revision ID: ed52bb8c8bda
Revises: a58205bdc740
Create Date: 2026-10-03 15:36:57.422705
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "ed52bb8c8bda"
down_revision: Union[str, None] = "a58205bdc740"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cards", sa.Column("topic_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_cards_topic_id"), "cards", ["topic_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_cards_topic_id_topics"),
        "cards",
        "topics",
        ["topic_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_unique_constraint(
        "uq_topics_subject_id_name", "topics", ["subject_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_topics_subject_id_name", "topics", type_="unique")
    op.drop_constraint(op.f("fk_cards_topic_id_topics"), "cards", type_="foreignkey")
    op.drop_index(op.f("ix_cards_topic_id"), table_name="cards")
    op.drop_column("cards", "topic_id")
    # ### end Alembic commands ###
